INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Futuna',-178.1228,-14.3056,86,'Cook Islands','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Shelley Point',17.9500,-32.7100,86,'South Africa','JANUARY');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Anakao',43.6460,-23.6717,87,'South Africa','APRIL');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Cubagua',-64.1600,10.8200,87,'Venezuela','APRIL');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Fishermen''s Bay',59.6700,22.0300,87,'Oman','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Pocitas Beach',-81.0800,-4.1100,87,'Ecuador','OCTOBER');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Zapara',-71.5667,10.9866,87,'Venezuela','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('2nd Bay',-9.7800,31.4800,88,'Morocco','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Adicora',-69.8000,11.9300,88,'Venezuela','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Bahia de San Pedro',-63.9800,10.8000,88,'Venezuela','APRIL');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Bunker Beach',115.0400,-33.5400,88,'Australia','JANUARY');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Dolphin beach, Guns',14.5400,-22.8445,88,'South Africa','OCTOBER');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Essaouira',-9.7636,31.5019,88,'Morocco','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Isla Holbox',-87.2500,21.5500,88,'Mexico','APRIL');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Nunura',-81.1200,-5.8400,88,'Ecuador','APRIL');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Diego Suarez - Baie d''Andovokonko',49.3968,-12.2889,89,'Tanzania','OCTOBER');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Langebaan',18.0300,-33.0800,89,'South Africa','JANUARY');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Observatory Beach',121.7700,-33.9000,89,'Australia','JANUARY');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Phan Thiet',108.8000,10.7000,89,'Viet Nam','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Pimentel',-79.9300,-6.8400,89,'Peru','APRIL');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Sidi Abdellah',-9.4700,31.9000,89,'Morocco','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Alibaba',-22.9700,16.7100,90,'Senegal','APRIL');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Bandy Creek',122.0000,-33.8200,90,'Australia','JANUARY');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Barra Grande',-41.4117,-2.9100,90,'Brazil','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Bequia',-61.2400,13.0100,90,'Guadeloupe','APRIL');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Punta Abreojos',-113.5700,26.7000,90,'Mexico','APRIL');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Farwah',11.7000,33.1200,91,'Libya','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Jeddah, South Corniche',39.3508,20.8704,91,'Saudi Arabia','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Lagoon',108.9500,10.5400,91,'Viet Nam','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Puerto Caballos',-75.4900,-14.9400,91,'Peru','APRIL');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Fourth Mile Beach',121.8200,-33.8900,92,'Australia','JANUARY');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Kaliantan Lombok',116.4841,-8.9156,92,'Indonesia','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Limassol, Anemometer',33.0235,34.6520,92,'United Kingdom','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Los Roques',-66.6700,11.9500,92,'Venezuela','APRIL');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Namena Island',179.0998,-17.1098,92,'New Zealand','APRIL');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Zanzibar / Ras Nungwi',39.2986,-5.7229,92,'Tanzania','JANUARY');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Al Mirfa',53.4844,24.1026,93,'United Arab Emirates','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Dakar',-17.4300,14.6700,93,'Senegal','APRIL');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Exmouth (Dunes)',114.1388,-21.8002,93,'Australia','OCTOBER');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Geraldton',114.6000,-28.7600,93,'Australia','OCTOBER');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Point Moore',114.5700,-28.7800,93,'Australia','OCTOBER');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Walvis Bay',14.4800,-22.9000,93,'South Africa','OCTOBER');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Cabo de La Vela',-72.1479,12.1934,94,'Venezuela','APRIL');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('DOSC, Dubai Offshore Sailing Club',55.2153,25.1758,94,'United Arab Emirates','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('HERZLIA SEA SCOUTS',34.8007,32.1737,94,'Israel','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Sal / Santa Maria',-22.9090,16.5920,94,'Senegal','APRIL');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Shark Bay',18.0452,-33.1135,94,'South Africa','JANUARY');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Sorobon',-68.2300,12.0900,94,'Venezuela','APRIL');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Adam''s Bridge',79.5686,9.0869,95,'Sri Lanka','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Boa Vista',-22.8000,16.1000,95,'Senegal','APRIL');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Gazebo Point',58.9100,20.6600,95,'Oman','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Kalpitiya',79.7017,8.0810,95,'Sri Lanka','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Kappalady',79.7060,8.1408,95,'Sri Lanka','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('North Obhur, Danah Jed',39.0616,21.7483,95,'Saudi Arabia','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Oualidia-Lagune',-9.0400,32.7400,95,'Morocco','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Lavanono',44.9300,-25.4200,96,'South Africa','OCTOBER');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Androka',44.0600,-25.0200,97,'South Africa','OCTOBER');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Dakhla',-15.8540,23.7400,97,'Spain','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Heliophora Lagoon',-15.8564,23.6371,97,'Spain','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Golden Beach',33.7209,27.3136,98,'Egypt','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Tamania (Cap 8)',-14.8393,25.0817,98,'Spain','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Jericoacoara',-40.5100,-2.7900,99,'Brazil','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Laayoune',-13.4400,27.0300,99,'Spain','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Marsa El Brega',20.0764,30.8995,99,'Libya','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('27-Waam',66.8381,24.4681,100,'India','APRIL');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Barra Nova',-38.1499,-4.1008,100,'Brazil','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Cumbuco',-38.7299,-3.6246,100,'Brazil','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Galinhos',-36.2900,-5.0800,100,'Brazil','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Guajiru',-39.2312,-3.2389,100,'Brazil','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Ilha do Guajiru',-39.9086,-2.8806,100,'Brazil','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Paracas, Kangaroo Kite Shack',-76.2552,-13.8589,100,'Peru','OCTOBER');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Socotra Island - Qualansiyah',53.5700,12.7200,100,'Oman','AUGUST');
INSERT INTO spots(name,longitude,latitude,windProbability,country,whenToGo) VALUES ('Westpunt (Westpoint)',-70.0594,12.6164,100,'Venezuela','APRIL');
